apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fabrikam-functions
  name: fabrikam-functions
  namespace: kafka  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabrikam-functions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fabrikam-functions
      
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "fabrikam-functions"
        dapr.io/app-port: "80"    
    spec:
      containers:
      - image: k3d-registry.localhost:5000/fabrikam-functions
        name: fabrikam-functions
        ports:
          - containerPort: 80
        resources: {}
status: {}

---


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fabrikam-functions
  name: fabrikam-functions
  namespace: kafka
spec:
  ports:
  - name: 8080-8080
    port: 8076
    protocol: TCP
    targetPort: 80
  selector:
    app: fabrikam-functions
  type: ClusterIP
status:
  loadBalancer: {}
