apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-function
  name: kafka-function 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-function
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-function
    spec:
      containers:
      - image: k3d-registry.localhost:5000/kafka-function:latest
        name: kafka-function
        
status: {}